main:
  mode: "inference"  # train/inference

dataset:
  path: "../data/assignment_1_data.npz"
  input: "inputs"
  output: "outputs"
  mesh: "grids"

model:
  modes: 6
  width: 32
  path: "../models/"

training: 
  batch_size: 18
  learning_rate: 0.001 
  epochs: 100
  step_size: 100
  gamma: 0.05 
  r: 8

outputs:
  path: "../outputs/"
