main:
  mode: "inference"  # train/inference

dataset:
  path: "../data/assignment_1_data.npz"
  input: "inputs"
  output: "outputs"
  mesh: "grids"

FNO:
  modes: 8
  width: 50
  use_batch_norm: True
  path: "../output_models/"

dlResNet:
  in_channels: 3
  out_channels_lst: [16, 32]
  dilations: [1,2,4,2,1]
  kernel_size: 1
  down_sample: False
  use_batch_norm: True
  path: "../output_models/"

training: 
  batch_size: 18
  learning_rate: 0.001 
  epochs: 200
  step_size: 50
  gamma: 0.05 
  r: 8

outputs:
  path: "../outputs/"
