main:
  mode: "inference"  # train/inference

dataset:
  path: "../data/assignment_1_data.npz"
  input: "inputs"
  output: "outputs"
  mesh: "grids"

FNO:
  modes: 6
  width: 32
  path: "../output_models/"

drResNet:
  in_channels: 3
  out_channels_lst: [16, 16]
  kernel_size: 1
  path: "../output_models/"

training: 
  batch_size: 18
  learning_rate: 0.001 
  epochs: 100
  step_size: 100
  gamma: 0.05 
  r: 8

outputs:
  path: "../outputs/"
